version: '3.8'

services:
  postgres:
    container_name: ticket-hub-server-pg
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticket-hub
